project:
  type: website

website:
  title: "DSCI Lab Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true



